inherit_gem:
  house_style: rails/rubocop.yml

AllCops:
  Exclude:
    - bin/*
    - Guardfile
    - vendor/**/*
    - db/**/*
    - node_modules/**/*
    - config/environments/*

Metrics/LineLength:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  Enabled: false
