inherit_gem:
  house_style: ruby/rubocop.yml
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - Gemfile
    - Guardfile
    - vendor/**/*
    - db/**/*
    - node_modules/**/*
    - config/environments/*
Metrics/LineLength:
  Exclude:
    - spec/**/*
