default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: rocksteady-development

test:
  <<: *default
  database: rocksteady-test

production:
  <<: *default
  database: rocksteady-production
